### ISSUE TITLE
请问为什么你的SDWebImage第三方库怎么找不到啊？

### ISSUE THREAD

**Issue by Piaoxianren** [bravekingzhang/swiftBookRecommend#1]
请问为什么你的SDWebImage第三方库怎么找不到啊？

**Comment by bravekingzhang** [comment]
shell 进入到 Podfile文件所在的那个目录，执行  
pod install
网络原因，sdwebimage比较大一点，可能需要多执行几次，

如果你没有安装cocoapods，那么需要新安装，具体，google下，很多文件教你如何安装cocoapods
